const Images = {
    "Taj Mahal": "/src/assets/Taj Mahal.jpeg",
    "Jaipur City Palace": "/src/assets/Jaipur City Palace.jpeg",
    "Goa Beaches": "/src/assets/Goa Beaches.jpeg",
    "Mysore Palace": "/src/assets/Mysore Palace.jpg",
    "Kerala Backwaters": "/src/assets/Kerala Backwaters.jpeg",
    "Darjeeling": "/src/assets/Darjeeling.jpeg",
    "Varanasi Ghats": "/src/assets/Varanasi Ghats.jpeg",
    "Rann of Kutch": "/src/assets/Rann of Kutch.jpeg",
    "Hampi": "/src/assets/Hampi.jpeg",
    "Khajuraho Temples": "/src/assets/Khajuraho Temples.jpeg",
    "Sundarbans": "/src/assets/Sundarbans.jpeg",
    "Victoria Memorial": "/src/assets/Victoria Memorial.jpeg",
    "Howrah Bridge": "/src/assets/Howrah Bridge.jpeg",
    "Bishnupur Temples": "/src/assets/Bishnupur Temples.jpeg",
    "Dakshineswar Kali Temple": "/src/assets/Dakshineswar Kali Temple.jpeg",
    "Moti Masjid": "/src/assets/Moti Masjid.jpeg",
    "Fatehpur Sikri": "/src/assets/Fatehpur Sikri.jpeg",
    "Mehtab Garden": "/src/assets/Mehtab Garden.jpeg",
    "Jantar Mantar": "/src/assets/Jantar Mantar.jpeg",
    "Sheesh Mahal": "/src/assets/Sheesh Mahal.jpeg",
    "Elephantastic": "/src/assets/Elephantastic.jpeg",
    "Fort Aguda": "/src/assets/Fort Aguda.jpeg",
    "Basilica of Bom Jesus": "/src/assets/Basilica of Bom Jesus.jpeg",
    "Cabo De Rama Fort": "/src/assets/Cabo De Rama Fort.jpeg",
    "Somnathpur Temple": "/src/assets/Somnathpur Temple.jpeg",
    "Sri Chamundeswari Temple": "/src/assets/Sri Chamundeswari Temple.jpg",
    "Mysore Sand Sculpural Museum": "/src/assets/Mysore Sand Sculptures.jpeg",
    "Padmanabhaswamy Temple": "/src/assets/Padmanabhaswamy Temple.cms",
    "Kovalam Beach": "/src/assets/Kovalam Beach.jpg",
    "Priyadarshini Planetorium": "/src/assets/Priyadarshini Planetarium.jpg",
    "Kanchenjunga Mountain": "/src/assets/Kanchenjunga Mountain.jpg",
    "Lamahatta": "/src/assets/Lamahatta.jpg",
    "Japanese Peace Pagoda": "/src/assets/Japanese Peace Pagoda.jpg",
    "Barbotey Rock Garden": "/src/assets/Barbotey Rock Garden.webp",
    "Dasawmedh Ghat": "/src/assets/Dasawmedh Ghat.jpg",
    "Manikarnika Ghat": "/src/assets/Manikarnika Ghat.jpeg",
    "Kashi Viswanath Temple": "/src/assets/Kashi Viswanath Temple.jpg",
    "Sarnath": "/src/assets/Sarnath.jpeg",
    "Batuk Bhairav Temple": "/src/assets/Batuk Bhairav Temple.jpg",
    "Kala Dungar": "/src/assets/Kala Dungar.jpg",
    "Little Rann of Kutch": "/src/assets/Little Rann of Kutch.webp",
    "Topansar Lake": "/src/assets/Topansar Lake.webp",
    "Virupaksha Temple": "/src/assets/Virupaksha Temple.webp",
    "Matanga Hill": "/src/assets/Matanga Hill.jpg",
    "Hazara Rama Temple": "/src/assets/Hazara Rama Temple.webp",
    "Kandariya Mahadev Temple": "/src/assets/Kandariya Mahadev Temple.jpg",
    "Tribal and Folk Art": "/src/assets/Tribal and Folk Art.jpg",
    "Panna Tiger Reserve": "/src/assets/Panna Tiger Reserve.webp",
    "Rushikonda Beach": "/src/assets/Rushikonda Beach.jpg",
    "Simhachalam Temple": "/src/assets/Simhachalam Temple.jpeg",
    "Vizag National Park": "/src/assets/Vizag National Park.jpeg",
    "Araku Burra Caves": "/src/assets/Araku Burra Caves.jpg",
    "Ramakrishna Beach": "/src/assets/Ramakrishna Beach.jpeg",
    "Vizag Steel Plant": "/src/assets/Vizag Steel Plant.jpg"
}

export default Images
