const Images = {
    "Taj Mahal": "client/src/assets/Taj Mahal.jpeg",
    "Jaipur City Palace": "client/src/assets/Jaipur City Palace.jpeg",
    "Goa Beaches": "client/src/assets/Goa Beaches.jpeg",
    "Mysore Palace": "client/src/assets/Mysore Palace.jpg",
    "Kerala Backwaters": "client/src/assets/Kerala Backwaters.jpeg",
    "Darjeeling": "client/src/assets/Darjeeling.jpeg",
    "Varanasi Ghats": "client/src/assets/Varanasi Ghats.jpeg",
    "Rann of Kutch": "client/src/assets/Rann of Kutch.jpeg",
    "Hampi": "client/src/assets/Hampi.jpeg",
    "Khajuraho Temples": "client/src/assets/Khajuraho Temples.jpeg",
    "Sundarbans": "client/src/assets/Sundarbans.jpeg",
    "Victoria Memorial": "client/src/assets/Victoria Memorial.jpeg",
    "Howrah Bridge": "client/src/assets/Howrah Bridge.jpeg",
    "Bishnupur Temples": "client/src/assets/Bishnupur Temples.jpeg",
    "Dakshineswar Kali Temple": "client/src/assets/Dakshineswar Kali Temple.jpeg",
    "Moti Masjid": "client/src/assets/Moti Masjid.jpeg",
    "Fatehpur Sikri": "client/src/assets/Fatehpur Sikri.jpeg",
    "Mehtab Garden": "client/src/assets/Mehtab Garden.jpeg",
    "Jantar Mantar": "client/src/assets/Jantar Mantar.jpeg",
    "Sheesh Mahal": "client/src/assets/Sheesh Mahal.jpeg",
    "Elephantastic": "client/src/assets/Elephantastic.jpeg",
    "Fort Aguda": "client/src/assets/Fort Aguda.jpeg",
    "Basilica of Bom Jesus": "client/src/assets/Basilica of Bom Jesus.jpeg",
    "Cabo De Rama Fort": "client/src/assets/Cabo De Rama Fort.jpeg",
    "Somnathpur Temple": "client/src/assets/Somnathpur Temple.jpeg",
    "Sri Chamundeswari Temple": "client/src/assets/Sri Chamundeswari Temple.jpg",
    "Mysore Sand Sculpural Museum": "client/src/assets/Mysore Sand Sculpural Museum.cms",
    "Padmanabhaswamy Temple": "client/src/assets/Padmanabhaswamy Temple.cms",
    "Kovalam Beach": "client/src/assets/Kovalam Beach.jpg",
    "Priyadarshini Planetorium": "client/src/assets/Priyadarshini Planetarium.jpg",
    "Kanchenjunga Mountain": "client/src/assets/Kanchenjunga Mountain.jpg",
    "Lamahatta": "client/src/assets/Lamahatta.jpg",
    "Japanese Peace Pagoda": "client/src/assets/Japanese Peace Pagoda.jpg",
    "Barbotey Rock Garden": "client/src/assets/Barbotey Rock Garden.webp",
    "Dasawmedh Ghat": "client/src/assets/Dasawmedh Ghat.jpg",
    "Manikarnika Ghat": "client/src/assets/Manikarnika Ghat.jpeg",
    "Kashi Viswanath Temple": "client/src/assets/Kashi Viswanath Temple.jpg",
    "Sarnath": "client/src/assets/Sarnath.jpeg",
    "Batuk Bhairav Temple": "client/src/assets/Batuk Bhairav Temple.jpg",
    "Kala Dungar": "client/src/assets/Kala Dungar.jpg",
    "Little Rann of Kutch": "client/src/assets/Little Rann of Kutch.webp",
    "Topansar Lake": "client/src/assets/Topansar Lake.webp",
    "Virupaksha Temple": "client/src/assets/Virupaksha Temple.webp",
    "Matanga Hill": "client/src/assets/Matanga Hill.jpg",
    "Hazara Rama Temple": "client/src/assets/Hazara Rama Temple.webp",
    "Kandariya Mahadev Temple": "client/src/assets/Kandariya Mahadev Temple.jpg",
    "Tribal and Folk Art": "client/src/assets/Tribal and Folk Art.jpg",
    "Panna Tiger Reserve": "client/src/assets/Panna Tiger Reserve.webp",
    "Rushikonda Beach": "client/src/assets/Rushikonda Beach.jpg",
    "Simhachalam Temple": "client/src/assets/Simhachalam Temple.jpeg",
    "Vizag National Park": "client/src/assets/Vizag National Park.jpeg",
    "Araku Burra Caves": "client/src/assets/Araku Burra Caves.jpg",
    "Ramakrishna Beach": "client/src/assets/Ramakrishna Beach.jpeg",
    "Vizag Steel Plant": "client/src/assets/Vizag Steel Plant.jpg"
}

export default Images
